# fly.toml app configuration file generated for mini-message-board-new-agabra23 on 2023-09-06T17:51:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mini-message-board-new-agabra23"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
